### ISSUE TITLE
Imagenet100 Reproduction Accuracy considerably lower than reported.

### ISSUE THREAD

**Issue by davidrzs** [vturrisi/solo-learn#346]
**Describe the bug**
Might not be a bug but your guidance is valued:

I tried to reproduce the imagenet100 results using Barlow Twins and get accuracies well below the officially reported figures.
![image](https://github.com/vturrisi/solo-learn/assets/18198078/2d1a20a8-a01b-4ded-9038-f8c19e6955b0)
The model trained for 400 epochs with the default configuration on 2 GPUs, but even when just training on 1 GPU the same accuracies can be observed. I suspect that 400 epochs is not enough (as the validation curve keeps increasing), hence I wanted to check if you really trained the models for 400 epochs. 

I suspect I am doing something wrong but I am unsure what my mistake is. Thanks for your guidance. 

For the dataset: We used [these](https://github.com/HobbitLong/CMC/blob/master/imagenet100.txt) classes as referenced [here](https://github.com/vturrisi/solo-learn/issues/116).

**To Reproduce**
`python /ssl_pm/main_pretrain.py --config-path scripts/pretrain/imagenet-100/ --config-name barlow.yaml`

**Screenshots**
![image](https://github.com/vturrisi/solo-learn/assets/18198078/29a1d5e8-40cd-45f5-a7da-86b7ac09bc54)

**Versions**
Latest version (pulled 2 days ago)

-- 
here you have my `barlow.yaml` file for reference:

```yaml
defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "barlow_twins-imagenet100"
method: "barlow_twins"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 2048
  scale_loss: 0.1
data:
  dataset: imagenet100
  train_path: "/itet-stor/zdavid/net_scratch/ILSVRC2012_img_train_100" #"/home/david/data/imagenet_100/train"
  val_path: "/itet-stor/zdavid/net_scratch/ILSVRC2012_img_val_100" #"/home/david/data/imagenet_100/val"
  format: "dali"
  num_workers: 4
optimizer:
  name: "lars"
  batch_size: 128
  lr: 0.3
  classifier_lr: 0.1
  weight_decay: 1e-4
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: False

# overwrite PL stuff
max_epochs: 400
devices: [0, 1]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed
```
