### ISSUE TITLE
SimCLR for specific domain

### ISSUE THREAD

**Issue by miguel-arrf** [vturrisi/solo-learn#349]
Hello!

I've been trying to use this library for a downstream task of segmentation. 

I want to use SimCLR. I've been looking at the `main_pretrain.py` file and there was something that got me confused.

What's the idea behind the `num_crops` parameter? Shouldn't we, for each image, augment it only once, and use that in the forward pass? 

My understanding is that for each image in our dataset, and implementing a custom Dataset, what the `__getitem__` would return would be a tuple, with the original image and the transformed one. **When isn't this the case?** :)

This is the augmentations file I have:

```
- mean: 52.722780748721
  std: 243.6154740715541
  rrc:
    enabled: False
    crop_min_scale: 0.08
    crop_max_scale: 1.0
  color_jitter:
    prob: 0.0
    brightness: 0.8
    contrast: 0.8
    saturation: 0.8
    hue: 0.0
  grayscale:
    prob: 0.0
  gaussian_blur:
    prob: 0.0
  solarization:
    prob: 0.0
  equalization:
    prob: 0.0
  horizontal_flip:
    prob: 1.0
  crop_size: [224,224]
  num_crops: 1

- mean: 52.722780748721
  std: 243.6154740715541
  rrc:
    enabled: False
  color_jitter:
    prob: 0.0
  grayscale:
    prob: 0.0
  gaussian_blur:
    prob: 0.0
  solarization:
    prob: 0.0
  equalization:
    prob: 0.0
  horizontal_flip:
    prob: 0.0
  crop_size: [224,224]
  num_crops: 1
```

I'm resizing all images to size (224,244). 

Thank you so much!
